// Token4AI Cloud Attribution
// Developed by the commercial cloud service company represented by https://token4ai.cloud.
// Author: jamesduan (X: https://x.com/JamesDuanL)
// Created: 2026-07-31
// description: Token4AI Cloud, FerroGate AI Gateway, the Node-side half of the
// #424 docker-free PoC harness: spawns the REAL `ferrogate run` binary plus a
// stub OpenAI-shaped upstream, so the Worker booted in workerd is proxying to an
// actual Pingora data plane rather than to a mock.

import { spawn, type ChildProcess } from "node:child_process";
import { createServer, type Server } from "node:http";
import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import { POC_MODEL, POC_VIRTUAL_KEY, UPSTREAM_COMPLETION } from "./fixtures";
import { gatewayPort, REPO_ROOT, upstreamPort } from "./ports";

let gateway: ChildProcess | undefined;
let upstream: Server | undefined;
let workDir: string | undefined;

/**
 * Locate the `ferrogate` binary.
 *
 * Deliberately does NOT build it. `scripts/check-workers.sh` runs in a
 * Node/npm-only lane (see AGENTS.md "CI Workflow Structure" and
 * .github/workflows/workers.yml), so invoking cargo from here would break that
 * contract. Missing binary is therefore a hard, named failure rather than a
 * skip: an unproven PoC must not read as a passing one.
 */
function resolveFerroGateBinary(): string {
  const explicit = process.env.FERROGATE_BIN;
  const candidates = explicit
    ? [explicit]
    : [
        path.join(REPO_ROOT, "target", "debug", "ferrogate"),
        path.join(REPO_ROOT, "target", "release", "ferrogate"),
      ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return candidate;
    }
  }
  throw new Error(
    [
      "ferrogate-poc harness: no `ferrogate` binary found.",
      `  looked at: ${candidates.join(", ")}`,
      "  build one with `cargo build -p ferrogate-cli`, or set FERROGATE_BIN=<path>.",
      "  This suite proxies to the real binary on purpose -- without it there is no PoC,",
      "  only a Worker talking to a mock, so it fails instead of skipping.",
    ].join("\n"),
  );
}

function pocConfig(): string {
  return `# generated by workers/ferrogate-poc/test/global-setup.ts -- do not edit
listen = "127.0.0.1:${gatewayPort()}"

# Local cluster state so /readyz has a real backend to report on. The deployed
# PoC points [storage] at external Postgres instead (see poc.toml); that path is
# runbook step P6 and cannot be proven off Cloudflare.
[cluster]
enabled = true
cluster_id = "ferrogate-poc"
node_id = "poc-node"
node_region = "local"
node_zone = "local-a"
state_backend = "local"
counter_backend = "local"
heartbeat_interval_secs = 10
config_poll_interval_secs = 5

[[providers]]
name = "openai"
kind = "openai"
base_url = "http://127.0.0.1:${upstreamPort()}/v1"
api_key_env = "FERROGATE_POC_PROVIDER_KEY"

[[models]]
name = "${POC_MODEL}"
provider = "openai"
provider_model = "gpt-4o-mini"
capabilities = ["chat", "streaming"]
input_price_per_1m = 0.15
output_price_per_1m = 0.6

[[api_keys]]
id = "key_poc"
name = "PoC key"
key = "${POC_VIRTUAL_KEY}"
scopes = ["models.read", "chat.completions"]
allowed_models = ["${POC_MODEL}"]
`;
}

function startUpstream(): Promise<Server> {
  return new Promise((resolve, reject) => {
    const server = createServer((request, response) => {
      // Drain the body: FerroGate sends a request body, and not reading it can
      // stall the socket.
      request.resume();
      request.on("end", () => {
        response.writeHead(200, { "content-type": "application/json" });
        response.end(JSON.stringify(UPSTREAM_COMPLETION));
      });
    });
    server.on("error", reject);
    server.listen(upstreamPort(), "127.0.0.1", () => resolve(server));
  });
}

async function waitForGateway(): Promise<void> {
  const deadline = Date.now() + 30_000;
  let lastError = "no attempt made";
  while (Date.now() < deadline) {
    if (gateway?.exitCode !== null && gateway?.exitCode !== undefined) {
      throw new Error(`ferrogate exited early with code ${gateway.exitCode}`);
    }
    try {
      const response = await fetch(`http://127.0.0.1:${gatewayPort()}/healthz`);
      if (response.ok) {
        return;
      }
      lastError = `HTTP ${response.status}`;
    } catch (error) {
      lastError = String(error);
    }
    await new Promise((resolve) => setTimeout(resolve, 200));
  }
  throw new Error(`ferrogate-poc harness: gateway did not become healthy in 30s (${lastError})`);
}

export async function setup(): Promise<void> {
  const binary = resolveFerroGateBinary();
  upstream = await startUpstream();

  workDir = mkdtempSync(path.join(tmpdir(), "ferrogate-poc-"));
  const configPath = path.join(workDir, "poc-harness.toml");
  writeFileSync(configPath, pocConfig());

  gateway = spawn(binary, ["run", "--config", configPath], {
    stdio: "ignore",
    env: { ...process.env, FERROGATE_POC_PROVIDER_KEY: "poc-upstream-key" },
  });
  gateway.on("error", (error) => {
    throw new Error(`ferrogate-poc harness: failed to spawn ${binary}: ${error}`);
  });

  await waitForGateway();
}

export async function teardown(): Promise<void> {
  gateway?.kill("SIGKILL");
  gateway = undefined;
  await new Promise<void>((resolve) => {
    if (!upstream) {
      resolve();
      return;
    }
    upstream.close(() => resolve());
  });
  upstream = undefined;
  if (workDir) {
    rmSync(workDir, { recursive: true, force: true });
    workDir = undefined;
  }
}
