import { readFileSync, writeFileSync } from "node:fs";
import { cloudflareTest, readD1Migrations } from "@cloudflare/vitest-pool-workers";
import { defineConfig } from "vitest/config";

/** The committed deploy config, read here because workerd has no filesystem. */
const WRANGLER_TOML = readFileSync(new URL("./wrangler.toml", import.meta.url), "utf8");

/**
 * THE ONE STANZA AN OFFLINE TEST POOL CANNOT LOAD — `[ai]` (issue #673).
 *
 * `wrangler.toml` declares `[ai] binding = "AI"` because the deployed Worker
 * genuinely reads it: `src/inference/workers-ai.ts` dispatches the `workers-ai`
 * provider family through it, and `src/guardrails/config.ts` reads it for the
 * Llama-Guard detector. But `@cloudflare/vitest-pool-workers` classifies the AI
 * binding as `DO-NOT-USE-this-resource-will-never-have-a-local-simulator`, and
 * wrangler refuses outright:
 *
 *   Error: AI bindings do not support local development. You can set
 *   `remote: true` for the binding definition in your configuration file to
 *   access a remote version of the resource.
 *
 * — while `remote: true` opens a proxy session against the live Cloudflare API,
 * which with no `CLOUDFLARE_API_TOKEN` fails the ENTIRE gateway suite before a
 * single test file is imported. Neither the per-binding `remote = false` nor the
 * pool's `remoteBindings: false` avoids it: `pickRemoteBindings` ignores the
 * first (the AI binding is unconditionally "remote"), and the second only skips
 * the proxy and then hits the refusal above. There is no third option today.
 *
 * So the pool is pointed at a DERIVED config — the committed file with exactly
 * the `[ai]` stanza removed — while `TEST_WRANGLER_TOML` below still binds the
 * COMMITTED text verbatim, so `test/wrangler-bindings.test.ts` and
 * `test/cron-trigger.test.ts` keep asserting against the real deploy config and
 * cannot be fooled by this substitution. `test/inference/workers-ai.test.ts`
 * additionally asserts that the derived file differs from the committed one in
 * the `[ai]` stanza and NOTHING else, so this cannot quietly grow into a second,
 * divergent deploy config.
 */
function stripAiStanza(toml: string): string {
  const kept: string[] = [];
  let inAi = false;
  for (const line of toml.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (trimmed === "[ai]") {
      inAi = true;
      continue;
    }
    // A stanza ends at the next table header, and nowhere else.
    if (inAi && trimmed.startsWith("[")) {
      inAi = false;
    }
    if (!inAi) kept.push(line);
  }
  return kept.join("\n");
}

/**
 * Written NEXT TO the committed config so every relative path inside it
 * (`main`, `migrations_dir`, …) resolves identically. Regenerated on every run
 * and gitignored — it is a build artifact of this file, never a config anyone
 * edits.
 */
writeFileSync(
  new URL("./wrangler.vitest.toml", import.meta.url),
  "# GENERATED by vitest.config.ts from wrangler.toml - DO NOT EDIT, DO NOT COMMIT.\n" +
    "# The committed wrangler.toml minus its [ai] stanza; see stripAiStanza() in\n" +
    "# vitest.config.ts for why that stanza cannot be loaded by an offline pool.\n" +
    stripAiStanza(WRANGLER_TOML),
);

/**
 * The REAL tenant-database migration, read from the same directory
 * `wrangler.toml`'s `migrations_dir` points `wrangler d1 migrations apply` at.
 * `test/setup-d1.ts` applies it to `env.DB` before every test file.
 *
 * This is not optional plumbing. `wrangler.toml` now declares
 * `[[d1_databases]] binding = "DB"`, which makes `depsFromEnv` build the D1
 * key resolver as the PRIMARY credential source — and a bound `DB` whose
 * `api_keys` table does not exist raises `ApiKeyStoreUnavailable`, i.e. every
 * bearer request in this suite would answer 503 instead of falling through to
 * the config keys below. Running the deployed migration rather than a fixture
 * copy is also what keeps the tests honest: a column rename in the migration
 * breaks them, instead of them passing against a private schema.
 */
const migrations = await readD1Migrations("../../sql/d1-ts/tenant");

/**
 * Test fixtures for the contract-driven auth middleware.
 *
 * The default adapters (`src/adapters.ts`) read their key/tenancy/worker tables
 * out of Worker vars, so the whole 401-vs-403 taxonomy is exercisable in real
 * `workerd` with no bindings and no network. Production supplies the same ports
 * from D1 / Secrets Store instead.
 */
const NATIVE_API_KEYS = [
  // A healthy durable/native key.
  {
    key: "fg_tenant_tools",
    id: "key_tools",
    tenant_id: "tenant_a",
    scopes: ["tools.read", "tools.execute"],
  },
  // SUSPENDED native key — must answer 401 `invalid_api_key`, never 403.
  {
    key: "fg_tenant_suspended",
    id: "key_suspended",
    tenant_id: "tenant_a",
    scopes: ["tools.read"],
    enabled: false,
  },
  // Authenticated but under-scoped — must answer 403 `scope_denied`.
  {
    key: "fg_tenant_readonly",
    id: "key_readonly",
    tenant_id: "tenant_a",
    scopes: ["skills.read"],
  },
  // Healthy key belonging to a SUSPENDED TENANT — 403 `tenancy_suspended`.
  {
    key: "fg_tenant_b_tools",
    id: "key_tenant_b",
    tenant_id: "tenant_b",
    scopes: ["tools.read"],
  },
  // Durable key with an EMPTY scope set: data-plane scopes only, never admin.
  { key: "fg_tenant_unscoped", id: "key_unscoped", tenant_id: "tenant_a", scopes: [] },
];

const STATIC_API_KEYS = [
  // Operator-authored static key, no scopes listed => all access.
  { key: "fg_root", id: "key_root", platform_operator: true },
  // Static keys report their state: disabled/expired are 403, not 401.
  { key: "fg_static_disabled", id: "key_static_disabled", tenant_id: "tenant_a", enabled: false },
  {
    key: "fg_static_expired",
    id: "key_static_expired",
    tenant_id: "tenant_a",
    expires_at_unix: 1,
  },
];

const SELF_HOSTED_WORKER_REGISTRY = [
  {
    worker_id: "worker_1",
    tenant_id: "tenant_a",
    workspace_id: "workspace_1",
    identity_fingerprint: "fingerprint_1",
    transport_secret: "worker_secret_1",
  },
];

/**
 * The auxiliary Worker `[[services]] binding = "TELEMETRY_COLLECTOR"` names.
 *
 * NOT optional plumbing, and not a stand-in for a test double. `wrangler.toml`
 * declares the service binding to `ferrogate-telemetry` (`apps/telemetry`), and
 * miniflare resolves a service binding against the set of workers it was given:
 * with the target undefined the RUNTIME REFUSES TO START —
 *
 *   Worker "core:user:vitest-pool-workers-runner-"'s binding
 *   "TELEMETRY_COLLECTOR" refers to a service "core:user:ferrogate-telemetry",
 *   but no such service is defined.
 *
 * — and every test file in this project errors before it is imported. (Real
 * `wrangler dev` is more forgiving: it boots and reports the binding as
 * `[not connected]`.)
 *
 * It answers 204 and records nothing on purpose. The gateway emits ONLY when
 * `TELEMETRY_TOKEN` is set, and this config sets no token, so nothing here is
 * ever reached in the default suite — `test/telemetry/mount.test.ts` installs
 * its own RECORDING collector plus a token on `env` and asserts against that.
 * Making this one recording as well would create a second, ambient sink whose
 * contents no test reads.
 */
const TELEMETRY_COLLECTOR_STUB = {
  name: "ferrogate-telemetry",
  modules: true,
  script: "export default { fetch: () => new Response(null, { status: 204 }) };",
} as const;

export default defineConfig({
  plugins: [
    cloudflareTest({
      // The DERIVED config, not the committed one — see {@link stripAiStanza}.
      // `TEST_WRANGLER_TOML` below still binds the committed text verbatim, so
      // every assertion about the real deploy config keeps holding.
      wrangler: { configPath: "./wrangler.vitest.toml" },
      // No remote-binding proxy: this suite is hermetic and has no Cloudflare
      // credentials. With `[ai]` stripped there is nothing remote left to proxy,
      // so this is belt-and-braces against a future remote binding landing and
      // silently making the suite require a network and an account.
      remoteBindings: false,
      miniflare: {
        bindings: {
          GATEWAY_NATIVE_API_KEYS: JSON.stringify(NATIVE_API_KEYS),
          GATEWAY_STATIC_API_KEYS: JSON.stringify(STATIC_API_KEYS),
          SELF_HOSTED_WORKER_REGISTRY: JSON.stringify(SELF_HOSTED_WORKER_REGISTRY),
          TENANCY_LIFECYCLE: JSON.stringify({ tenant_b: "suspended" }),
          TENANT_RBAC_ACTIONS: JSON.stringify({ tenant_a: ["guardrails.policy.read"] }),
          // Pinned EMPTY so the suite is hermetic. `wrangler: { configPath }`
          // makes miniflare load `apps/gateway/.dev.vars` too, and that file is
          // gitignored local developer state — a machine that has one
          // configured with a real provider/model (for the separate cloud
          // verification) made `test/contract.test.ts`'s "empty registry ⇒
          // `{object:"list",data:[]}`" assertion fail on an otherwise correct
          // tree. An explicit binding wins over `.dev.vars`, so the registry the
          // suite sees is the one the suite states, on every machine.
          GATEWAY_PROVIDERS: "[]",
          GATEWAY_MODELS: "[]",
          TEST_D1_SCHEMA: migrations,
          // The COMMITTED deploy config, verbatim, so a test can assert against
          // the parts of it that no binding surfaces. `[triggers] crons` is the
          // one that matters: workerd never dispatches a scheduled event under
          // vitest, so the whole suite stays green on a Worker whose Cron was
          // deleted — the billing-outbox recovery would simply never fire in
          // production. `test/cron-trigger.test.ts` reads this.
          TEST_WRANGLER_TOML: WRANGLER_TOML,
        },
        workers: [TELEMETRY_COLLECTOR_STUB],
      },
    }),
  ],
  test: {
    include: ["test/**/*.test.ts"],
    setupFiles: ["./test/setup-d1.ts"],
  },
});
