apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ferrogate.fullname" . }}-config
  labels:
    {{- include "ferrogate.labels" . | nindent 4 }}
data:
  ferrogate.toml: |
{{ tpl .Values.config . | indent 4 }}
