export const APP_ROUTES = {
  dashboard: "/app",
  assets: "/app/assets",
  withheldAssets: "/app/withheld-assets",
  tenantResolvedDefaults: "/app/tenant-resolved-defaults",
  toolApprovals: "/app/tool-approvals",
  agentRuns: "/app/agent-runs",
  agentRunDetail: "/app/agent-runs/:runId",
  agentSchedules: "/app/agent-schedules",
  guardrailPolicies: "/app/guardrail-policies",
  guardrailPolicyDetail: "/app/guardrail-policies/:policyId",
  guardrailEvaluations: "/app/guardrail-evaluations",
  investigations: "/app/investigations",
  wallets: "/app/wallets",
  paymentMethods: "/app/payment-methods",
  billingDeadLetters: "/app/billing-dead-letters",
  metering: "/app/metering",
  selfHostedWorkerOperations: "/app/workers/self-hosted",
  selfHostedWorkerDetail: "/app/workers/self-hosted/:workerId",
  selfHostedRuns: "/app/workers/self-hosted-runs",
  managedWorkerSessions: "/app/workers/managed-sessions",
  operationsStatus: "/app/ops/status",
  operationsConfig: "/app/ops/config",
  operationsDrain: "/app/ops/drain",
  operationsGatewayConfigs: "/app/ops/gateway-configs",
  operationsProviderHealth: "/app/ops/provider-health",
  operationsObservability: "/app/ops/observability",
  virtualKeys: "/app/api-keys",
  tenantRoles: "/app/tenant-roles",
  staticSites: "/app/static-sites",
  siteDomains: "/app/site-domains",
  mcpIdentities: "/app/mcp-identities",
  tools: "/app/tools",
  pluginTools: "/app/plugins/:pluginId/tools",
  toolSessions: "/app/tool-sessions",
} as const;

export const APP_DETAIL_ROUTE_PARENTS: Readonly<Record<string, string>> = {
  [APP_ROUTES.agentRunDetail]: APP_ROUTES.agentRuns,
  [APP_ROUTES.guardrailPolicyDetail]: APP_ROUTES.guardrailPolicies,
  [APP_ROUTES.selfHostedWorkerDetail]: APP_ROUTES.selfHostedWorkerOperations,
  [APP_ROUTES.pluginTools]: "/app/plugins",
};
