# GENERATED FILE - DO NOT EDIT.
# Source contract: docs/openapi/admin-api.openapi.json (repo root).
# Regenerate with: bun run generate   (from the repo root).

from __future__ import annotations

from typing import Final, TypedDict


SecurityScheme = tuple[str, tuple[str, ...]]
SecurityRequirement = tuple[SecurityScheme, ...]
SecurityRequirements = tuple[SecurityRequirement, ...]

class Operation(TypedDict):
    method: str
    path: str
    security: SecurityRequirements
    tags: tuple[str, ...]

OPENAPI_OPERATION_COUNT: Final[int] = 329

OPERATIONS: Final[dict[str, Operation]] = {
    "abortAssetUpload": {
        "method": "POST",
        "path": "/v1/assets/presign/abort/{asset_type}/{name}/{version}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "acknowledgeSelfHostedWorkerRun": {
        "method": "POST",
        "path": "/v1/self-hosted-workers/runs/ack",
        "security": ((("selfHostedTransport", ()),),),
        "tags": ("internal",),
    },
    "activateGuardrailPolicyRevision": {
        "method": "POST",
        "path": "/admin/v1/guardrail-policies/{policy_id}/activate",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "adjustWallet": {
        "method": "POST",
        "path": "/admin/v1/wallets/{tenant_id}/adjust",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "approveAdminToolApproval": {
        "method": "POST",
        "path": "/admin/v1/tool-approvals/{approval_id}/approve",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "archiveAdminPromptTemplate": {
        "method": "DELETE",
        "path": "/admin/v1/prompt-templates/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "archiveGuardrailPolicyRevision": {
        "method": "DELETE",
        "path": "/admin/v1/guardrail-policies/{policy_id}/revisions/{revision}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "assignTenantPlan": {
        "method": "PUT",
        "path": "/admin/v1/tenant-accounts/{tenant_id}/plan",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "authorizeMcpIdentity": {
        "method": "POST",
        "path": "/v1/mcp/identity/{server}/authorize",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "backfillControlStorage": {
        "method": "POST",
        "path": "/admin/v1/control-backfill",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "bindBillingGroupProvider": {
        "method": "PUT",
        "path": "/admin/v1/billing-groups/{id}/providers/{providerId}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "bindSiteDomain": {
        "method": "POST",
        "path": "/admin/v1/site-domains",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "bindTenantRole": {
        "method": "POST",
        "path": "/admin/v1/tenant-roles/{tenant_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "cancelAgentJob": {
        "method": "POST",
        "path": "/v1/agent-jobs/{run_id}/cancel",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "cancelBatch": {
        "method": "POST",
        "path": "/v1/batches/{batch_id}/cancel",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "chargeWallet": {
        "method": "POST",
        "path": "/admin/v1/wallets/{tenant_id}/charge",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "commitAssetUpload": {
        "method": "POST",
        "path": "/v1/assets/presign/commit/{asset_type}/{name}/{version}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "completeMcpIdentityOauth": {
        "method": "GET",
        "path": "/v1/mcp/identity/callback",
        "security": (),
        "tags": ("gateway",),
    },
    "countMessageTokens": {
        "method": "POST",
        "path": "/v1/messages/count_tokens",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createAdminAgentSchedule": {
        "method": "POST",
        "path": "/admin/v1/agent-schedules",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAdminAgentUpstream": {
        "method": "POST",
        "path": "/admin/v1/agent-upstreams",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "createAdminAgentWorkflow": {
        "method": "POST",
        "path": "/admin/v1/agent-workflows",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAdminApiKey": {
        "method": "POST",
        "path": "/admin/v1/api-keys",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAdminGatewayConfig": {
        "method": "POST",
        "path": "/admin/v1/gateway-configs",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAdminMcpServer": {
        "method": "POST",
        "path": "/admin/v1/mcp-servers",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAdminModel": {
        "method": "POST",
        "path": "/admin/v1/models",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAdminModelOffering": {
        "method": "POST",
        "path": "/admin/v1/models/{model_id}/offerings",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAdminPlugin": {
        "method": "POST",
        "path": "/admin/v1/plugins",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAdminPolicy": {
        "method": "POST",
        "path": "/admin/v1/policies",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAdminPromptTemplate": {
        "method": "POST",
        "path": "/admin/v1/prompt-templates",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAdminProvider": {
        "method": "POST",
        "path": "/admin/v1/providers",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAdminSkillPackage": {
        "method": "POST",
        "path": "/admin/v1/skill-packages",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "createAgentRun": {
        "method": "POST",
        "path": "/v1/agent-runs",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createAnnouncement": {
        "method": "POST",
        "path": "/admin/v1/announcements",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createAssetUploadIntent": {
        "method": "POST",
        "path": "/v1/assets/presign/upload/{asset_type}/{name}/{version}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createBatch": {
        "method": "POST",
        "path": "/v1/batches",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createBillingGroup": {
        "method": "POST",
        "path": "/admin/v1/billing-groups",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createChatCompletion": {
        "method": "POST",
        "path": "/v1/chat/completions",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createEmbedding": {
        "method": "POST",
        "path": "/v1/embeddings",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createFile": {
        "method": "POST",
        "path": "/v1/files",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createGuardrailPolicyRevision": {
        "method": "POST",
        "path": "/admin/v1/guardrail-policies",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createImage": {
        "method": "POST",
        "path": "/v1/images/generations",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createMessage": {
        "method": "POST",
        "path": "/v1/messages",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createNextGuardrailPolicyRevision": {
        "method": "POST",
        "path": "/admin/v1/guardrail-policies/{policy_id}/revisions",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createPaymentMethod": {
        "method": "POST",
        "path": "/admin/v1/payment-methods",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createPermission": {
        "method": "POST",
        "path": "/admin/v1/permissions",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createPlan": {
        "method": "POST",
        "path": "/admin/v1/plans",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createProject": {
        "method": "POST",
        "path": "/admin/v1/projects",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createQuotaPolicy": {
        "method": "POST",
        "path": "/admin/v1/quota-policies",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createRerank": {
        "method": "POST",
        "path": "/v1/rerank",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createResponse": {
        "method": "POST",
        "path": "/v1/responses",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createRole": {
        "method": "POST",
        "path": "/admin/v1/roles",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createSemanticCachePolicy": {
        "method": "POST",
        "path": "/admin/v1/semantic-cache-policies",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createSpeech": {
        "method": "POST",
        "path": "/v1/audio/speech",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createTenantAccount": {
        "method": "POST",
        "path": "/admin/v1/tenant-accounts",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createTranscription": {
        "method": "POST",
        "path": "/v1/audio/transcriptions",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createTranslation": {
        "method": "POST",
        "path": "/v1/audio/translations",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "createVirtualKey": {
        "method": "POST",
        "path": "/admin/v1/virtual-keys",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createWallet": {
        "method": "POST",
        "path": "/admin/v1/wallets",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "createWorkspace": {
        "method": "POST",
        "path": "/admin/v1/workspaces",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminAgentSchedule": {
        "method": "DELETE",
        "path": "/admin/v1/agent-schedules/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminAgentUpstream": {
        "method": "DELETE",
        "path": "/admin/v1/agent-upstreams/{id}",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "deleteAdminAgentWorkflow": {
        "method": "DELETE",
        "path": "/admin/v1/agent-workflows/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminApiKey": {
        "method": "DELETE",
        "path": "/admin/v1/api-keys/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminGatewayConfig": {
        "method": "DELETE",
        "path": "/admin/v1/gateway-configs/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminMcpServer": {
        "method": "DELETE",
        "path": "/admin/v1/mcp-servers/{name}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminModel": {
        "method": "DELETE",
        "path": "/admin/v1/models/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminModelOffering": {
        "method": "DELETE",
        "path": "/admin/v1/models/{model_id}/offerings/{offering_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminPlugin": {
        "method": "DELETE",
        "path": "/admin/v1/plugins/{plugin_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminPolicy": {
        "method": "DELETE",
        "path": "/admin/v1/policies/{name}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminPromptTemplateLabel": {
        "method": "DELETE",
        "path": "/admin/v1/prompt-templates/{id}/labels/{label}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminProvider": {
        "method": "DELETE",
        "path": "/admin/v1/providers/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAdminSkillPackage": {
        "method": "DELETE",
        "path": "/admin/v1/skill-packages/{id}",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "deleteAnnouncement": {
        "method": "DELETE",
        "path": "/admin/v1/announcements/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteAsset": {
        "method": "DELETE",
        "path": "/v1/assets/{asset_type}/{name}/{version}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "deleteAssetChannel": {
        "method": "DELETE",
        "path": "/v1/assets/{asset_type}/{name}/channels/{channel}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "deleteBillingGroup": {
        "method": "DELETE",
        "path": "/admin/v1/billing-groups/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteFile": {
        "method": "DELETE",
        "path": "/v1/files/{file_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "deletePaymentMethod": {
        "method": "DELETE",
        "path": "/admin/v1/payment-methods/{payment_method_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "deletePermission": {
        "method": "DELETE",
        "path": "/admin/v1/permissions/{permission_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "deleteProject": {
        "method": "DELETE",
        "path": "/admin/v1/projects/{project_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteQuotaPolicy": {
        "method": "DELETE",
        "path": "/admin/v1/quota-policies/{scope_type}/{scope_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "deleteResponse": {
        "method": "DELETE",
        "path": "/v1/responses/{response_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "deleteRole": {
        "method": "DELETE",
        "path": "/admin/v1/roles/{role_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "deleteSemanticCachePolicy": {
        "method": "DELETE",
        "path": "/admin/v1/semantic-cache-policies/{scope_type}/{scope_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "deleteWorkspace": {
        "method": "DELETE",
        "path": "/admin/v1/workspaces/{workspace_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "denyAdminToolApproval": {
        "method": "POST",
        "path": "/admin/v1/tool-approvals/{approval_id}/deny",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "disableVirtualKey": {
        "method": "POST",
        "path": "/admin/v1/virtual-keys/{key_id}/disable",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "dryRunGuardrailPolicyRevision": {
        "method": "POST",
        "path": "/admin/v1/guardrail-policies/{policy_id}/dry-run",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "enableVirtualKey": {
        "method": "POST",
        "path": "/admin/v1/virtual-keys/{key_id}/enable",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "evaluateX402SpendPolicy": {
        "method": "POST",
        "path": "/admin/v1/x402-spend-policies/evaluate",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "executeFunction": {
        "method": "POST",
        "path": "/v1/functions/execute",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "executeMcpTool": {
        "method": "POST",
        "path": "/v1/mcp/tool/execute",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "executeTool": {
        "method": "POST",
        "path": "/v1/tools/execute",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "expireAdminToolApproval": {
        "method": "POST",
        "path": "/admin/v1/tool-approvals/{approval_id}/expire",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "exportAdminCostRecords": {
        "method": "GET",
        "path": "/admin/v1/cost-record-exports",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "exportAdminRequestLogsJsonl": {
        "method": "GET",
        "path": "/admin/v1/request-log-exports",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "exportTenantData": {
        "method": "POST",
        "path": "/admin/v1/tenant-data/{tenant_id}/export",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "forceDeleteAssetVersion": {
        "method": "DELETE",
        "path": "/admin/v1/assets/{asset_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "getAdminAgentRunTimeline": {
        "method": "GET",
        "path": "/admin/v1/agent-runs/{run_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminAgentSchedule": {
        "method": "GET",
        "path": "/admin/v1/agent-schedules/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminAgentUpstream": {
        "method": "GET",
        "path": "/admin/v1/agent-upstreams/{id}",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "getAdminAgentWorkflow": {
        "method": "GET",
        "path": "/admin/v1/agent-workflows/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminApiKey": {
        "method": "GET",
        "path": "/admin/v1/api-keys/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminDashboard": {
        "method": "GET",
        "path": "/admin",
        "security": (),
        "tags": ("public",),
    },
    "getAdminDashboardAlias": {
        "method": "GET",
        "path": "/admin/dashboard",
        "security": (),
        "tags": ("gateway",),
    },
    "getAdminDashboardSlash": {
        "method": "GET",
        "path": "/admin/",
        "security": (),
        "tags": ("gateway",),
    },
    "getAdminDrain": {
        "method": "GET",
        "path": "/admin/v1/drain",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminExperiment": {
        "method": "GET",
        "path": "/admin/v1/experiments/{experiment_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminGatewayConfig": {
        "method": "GET",
        "path": "/admin/v1/gateway-configs/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminMcpServer": {
        "method": "GET",
        "path": "/admin/v1/mcp-servers/{name}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminModel": {
        "method": "GET",
        "path": "/admin/v1/models/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminModelOffering": {
        "method": "GET",
        "path": "/admin/v1/models/{model_id}/offerings/{offering_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminOverview": {
        "method": "GET",
        "path": "/admin/v1/overview",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminPlugin": {
        "method": "GET",
        "path": "/admin/v1/plugins/{plugin_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminPolicy": {
        "method": "GET",
        "path": "/admin/v1/policies/{name}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminPromptTemplate": {
        "method": "GET",
        "path": "/admin/v1/prompt-templates/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminProvider": {
        "method": "GET",
        "path": "/admin/v1/providers/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminSelfHostedRunTimeline": {
        "method": "GET",
        "path": "/admin/v1/self-hosted-runs/{run_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminSelfHostedWorker": {
        "method": "GET",
        "path": "/admin/v1/self-hosted-workers/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminSkillPackage": {
        "method": "GET",
        "path": "/admin/v1/skill-packages/{id}",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "getAdminStatus": {
        "method": "GET",
        "path": "/admin/v1/status",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminStatusAlias": {
        "method": "GET",
        "path": "/admin/status",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAdminToolApproval": {
        "method": "GET",
        "path": "/admin/v1/tool-approvals/{approval_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAgentDiscovery": {
        "method": "GET",
        "path": "/.well-known/agent.json",
        "security": ((("BearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Agent",),
    },
    "getAgentJob": {
        "method": "GET",
        "path": "/v1/agent-jobs/{run_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "getAgentJobResult": {
        "method": "GET",
        "path": "/v1/agent-jobs/{run_id}/result",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "getAgentSkill": {
        "method": "GET",
        "path": "/v1/skills/{id}",
        "security": ((("BearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Agent",),
    },
    "getAnnouncement": {
        "method": "GET",
        "path": "/admin/v1/announcements/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAsset": {
        "method": "GET",
        "path": "/v1/assets/{asset_type}/{name}/{version}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "getAssetDownloadUrl": {
        "method": "GET",
        "path": "/v1/assets/presign/download/{asset_type}/{name}/{version}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "getAssetManifest": {
        "method": "GET",
        "path": "/v1/assets/{asset_type}/{name}/manifest",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "getAssetRetentionPolicy": {
        "method": "GET",
        "path": "/admin/v1/retention-policies/{tenant_id}/{asset_type}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getAssetStorageSummary": {
        "method": "GET",
        "path": "/v1/assets/storage/summary",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "getBillingGroup": {
        "method": "GET",
        "path": "/admin/v1/billing-groups/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getEffectiveX402SpendPolicy": {
        "method": "GET",
        "path": "/admin/v1/x402-spend-policies/effective",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getFile": {
        "method": "GET",
        "path": "/v1/files/{file_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "getFileContent": {
        "method": "GET",
        "path": "/v1/files/{file_id}/content",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "getGuardrailInvestigation": {
        "method": "GET",
        "path": "/admin/v1/investigations",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getGuardrailPolicyRevision": {
        "method": "GET",
        "path": "/admin/v1/guardrail-policies/{policy_id}/revisions/{revision}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getHealthz": {
        "method": "GET",
        "path": "/healthz",
        "security": (),
        "tags": ("public",),
    },
    "getMcpIdentity": {
        "method": "GET",
        "path": "/v1/mcp/identity/{server}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "getMetrics": {
        "method": "GET",
        "path": "/metrics",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getModel": {
        "method": "GET",
        "path": "/v1/models/{model}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "getPaymentAttemptLinks": {
        "method": "GET",
        "path": "/admin/v1/payment-attempts/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getPermission": {
        "method": "GET",
        "path": "/admin/v1/permissions/{permission_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getPlan": {
        "method": "GET",
        "path": "/admin/v1/plans/{plan_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getProject": {
        "method": "GET",
        "path": "/admin/v1/projects/{project_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getQuotaPolicy": {
        "method": "GET",
        "path": "/admin/v1/quota-policies/{scope_type}/{scope_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getReadyz": {
        "method": "GET",
        "path": "/readyz",
        "security": (),
        "tags": ("public",),
    },
    "getResponse": {
        "method": "GET",
        "path": "/v1/responses/{response_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "getRole": {
        "method": "GET",
        "path": "/admin/v1/roles/{role_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getSemanticCachePolicy": {
        "method": "GET",
        "path": "/admin/v1/semantic-cache-policies/{scope_type}/{scope_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getSiteDomain": {
        "method": "GET",
        "path": "/admin/v1/site-domains/{hostname}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getTenantAccount": {
        "method": "GET",
        "path": "/admin/v1/tenant-accounts/{tenant_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getTenantResolvedDefaults": {
        "method": "GET",
        "path": "/admin/v1/tenant-accounts/{tenant_id}/resolved-defaults",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getVirtualKey": {
        "method": "GET",
        "path": "/admin/v1/virtual-keys/{key_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getWallet": {
        "method": "GET",
        "path": "/admin/v1/wallets/{tenant_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "getWorkspace": {
        "method": "GET",
        "path": "/admin/v1/workspaces/{workspace_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "importModelCatalog": {
        "method": "POST",
        "path": "/admin/v1/config/import-model-catalog",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "invalidateSemanticCachePolicy": {
        "method": "POST",
        "path": "/admin/v1/semantic-cache-policies/{scope_type}/{scope_id}/invalidate",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "invokeAgent": {
        "method": "POST",
        "path": "/v1/agents/{name}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "listAdminAgentCostBurn": {
        "method": "GET",
        "path": "/admin/v1/agent-cost-burn",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminAgentRuns": {
        "method": "GET",
        "path": "/admin/v1/agent-runs",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminAgentScheduleFires": {
        "method": "GET",
        "path": "/admin/v1/agent-schedules/{id}/fires",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminAgentSchedules": {
        "method": "GET",
        "path": "/admin/v1/agent-schedules",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminAgentUpstreams": {
        "method": "GET",
        "path": "/admin/v1/agent-upstreams",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "listAdminAgentWorkflows": {
        "method": "GET",
        "path": "/admin/v1/agent-workflows",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminApiKeys": {
        "method": "GET",
        "path": "/admin/v1/api-keys",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminAuditEvents": {
        "method": "GET",
        "path": "/admin/v1/audit-events",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminBillingEventsCompat": {
        "method": "GET",
        "path": "/admin/v1/billing-events",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminCostRecords": {
        "method": "GET",
        "path": "/admin/v1/cost-records",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminExperiments": {
        "method": "GET",
        "path": "/admin/v1/experiments",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminExtensions": {
        "method": "GET",
        "path": "/admin/v1/extensions",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminFrameworkAdapters": {
        "method": "GET",
        "path": "/admin/v1/framework-adapters",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminGatewayConfigs": {
        "method": "GET",
        "path": "/admin/v1/gateway-configs",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminManagedWorkerSessions": {
        "method": "GET",
        "path": "/admin/v1/managed-worker-sessions",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminManagedWorkers": {
        "method": "GET",
        "path": "/admin/v1/managed-workers",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminMcpServers": {
        "method": "GET",
        "path": "/admin/v1/mcp-servers",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminMeteringEvents": {
        "method": "GET",
        "path": "/admin/v1/metering-events",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminMeteringExportStatus": {
        "method": "GET",
        "path": "/admin/v1/metering-export-status",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminModelOfferings": {
        "method": "GET",
        "path": "/admin/v1/models/{model_id}/offerings",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminModels": {
        "method": "GET",
        "path": "/admin/v1/models",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminObservability": {
        "method": "GET",
        "path": "/admin/v1/observability",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminObservedAgentActivity": {
        "method": "GET",
        "path": "/admin/v1/observed-agent-activity",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminPluginTools": {
        "method": "GET",
        "path": "/admin/v1/plugins/{plugin_id}/tools",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminPlugins": {
        "method": "GET",
        "path": "/admin/v1/plugins",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminPolicies": {
        "method": "GET",
        "path": "/admin/v1/policies",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminPromptTemplateLabels": {
        "method": "GET",
        "path": "/admin/v1/prompt-templates/{id}/labels",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminPromptTemplates": {
        "method": "GET",
        "path": "/admin/v1/prompt-templates",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminProviderHealth": {
        "method": "GET",
        "path": "/admin/v1/provider-health",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminProviderModels": {
        "method": "GET",
        "path": "/admin/v1/provider-models",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminProviders": {
        "method": "GET",
        "path": "/admin/v1/providers",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminRequestLogs": {
        "method": "GET",
        "path": "/admin/v1/request-logs",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminSelfHostedWorkerRecords": {
        "method": "GET",
        "path": "/admin/v1/self-hosted-worker-records",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminSelfHostedWorkerTelemetryEvents": {
        "method": "GET",
        "path": "/admin/v1/self-hosted-workers/{id}/events",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminSelfHostedWorkers": {
        "method": "GET",
        "path": "/admin/v1/self-hosted-workers",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminSkillPackages": {
        "method": "GET",
        "path": "/admin/v1/skill-packages",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "listAdminSpendAnomalies": {
        "method": "GET",
        "path": "/admin/v1/spend-anomalies",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminTenants": {
        "method": "GET",
        "path": "/admin/v1/tenants",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminToolApprovals": {
        "method": "GET",
        "path": "/admin/v1/tool-approvals",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminToolSessionEvents": {
        "method": "GET",
        "path": "/admin/v1/tool-sessions/{session_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminTools": {
        "method": "GET",
        "path": "/admin/v1/tools",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAdminUsageAggregates": {
        "method": "GET",
        "path": "/admin/v1/usage-aggregates",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAgentJobEvents": {
        "method": "GET",
        "path": "/v1/agent-jobs/{run_id}/events",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "listAgentSkills": {
        "method": "GET",
        "path": "/v1/skills",
        "security": ((("BearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Agent",),
    },
    "listAnnouncements": {
        "method": "GET",
        "path": "/admin/v1/announcements",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listAssetChannels": {
        "method": "GET",
        "path": "/v1/assets/{asset_type}/{name}/channels",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "listAssets": {
        "method": "GET",
        "path": "/v1/assets",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "listAssetsByType": {
        "method": "GET",
        "path": "/v1/assets/{asset_type}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "listBatches": {
        "method": "GET",
        "path": "/v1/batches",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "listBillingGroups": {
        "method": "GET",
        "path": "/admin/v1/billing-groups",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listBillingOutboxDeadLetters": {
        "method": "GET",
        "path": "/admin/v1/billing-outbox-dead-letters",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listFiles": {
        "method": "GET",
        "path": "/v1/files",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "listFleetAssets": {
        "method": "GET",
        "path": "/admin/v1/assets",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listGuardrailEvaluations": {
        "method": "GET",
        "path": "/admin/v1/guardrail-evaluations",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listGuardrailPolicyRevisionHistory": {
        "method": "GET",
        "path": "/admin/v1/guardrail-policies/{policy_id}/revisions",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listGuardrailPolicyRevisions": {
        "method": "GET",
        "path": "/admin/v1/guardrail-policies",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listGuardrailPolicyRevisionsByPolicy": {
        "method": "GET",
        "path": "/admin/v1/guardrail-policies/{policy_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listModels": {
        "method": "GET",
        "path": "/v1/models",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "listPaymentAttempts": {
        "method": "GET",
        "path": "/admin/v1/payment-attempts",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listPaymentMethods": {
        "method": "GET",
        "path": "/admin/v1/payment-methods",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listPermissions": {
        "method": "GET",
        "path": "/admin/v1/permissions",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listPlans": {
        "method": "GET",
        "path": "/admin/v1/plans",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listProjects": {
        "method": "GET",
        "path": "/admin/v1/projects",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listProviderCredentials": {
        "method": "GET",
        "path": "/admin/v1/provider-credentials",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listQuarantinedAssets": {
        "method": "GET",
        "path": "/admin/v1/assets/quarantine",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listQuotaPolicies": {
        "method": "GET",
        "path": "/admin/v1/quota-policies",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listRoles": {
        "method": "GET",
        "path": "/admin/v1/roles",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listSemanticCachePolicies": {
        "method": "GET",
        "path": "/admin/v1/semantic-cache-policies",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listSharedBillingGroups": {
        "method": "GET",
        "path": "/admin/v1/shared-billing-groups",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listSiteDomains": {
        "method": "GET",
        "path": "/admin/v1/site-domains",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listTenantAccounts": {
        "method": "GET",
        "path": "/admin/v1/tenant-accounts",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listTenantRoles": {
        "method": "GET",
        "path": "/admin/v1/tenant-roles/{tenant_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listTools": {
        "method": "GET",
        "path": "/v1/tools",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "listUsageReports": {
        "method": "GET",
        "path": "/admin/v1/usage-reports",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listVirtualKeys": {
        "method": "GET",
        "path": "/admin/v1/virtual-keys",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listWalletLedger": {
        "method": "GET",
        "path": "/admin/v1/wallets/{tenant_id}/ledger",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listWallets": {
        "method": "GET",
        "path": "/admin/v1/wallets",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listWithheldAssets": {
        "method": "GET",
        "path": "/v1/assets/withheld",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "listWorkspaces": {
        "method": "GET",
        "path": "/admin/v1/workspaces",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "listX402SpendPolicies": {
        "method": "GET",
        "path": "/admin/v1/x402-spend-policies",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "mcpJsonRpc": {
        "method": "POST",
        "path": "/v1/mcp",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "migrateTenantStorage": {
        "method": "POST",
        "path": "/admin/v1/tenant-accounts/{tenant_id}/storage-migration",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchAdminAgentSchedule": {
        "method": "PATCH",
        "path": "/admin/v1/agent-schedules/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchAdminAgentUpstream": {
        "method": "PATCH",
        "path": "/admin/v1/agent-upstreams/{id}",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "patchAdminAgentWorkflow": {
        "method": "PATCH",
        "path": "/admin/v1/agent-workflows/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchAdminApiKey": {
        "method": "PATCH",
        "path": "/admin/v1/api-keys/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchAdminGatewayConfig": {
        "method": "PATCH",
        "path": "/admin/v1/gateway-configs/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchAdminMcpServer": {
        "method": "PATCH",
        "path": "/admin/v1/mcp-servers/{name}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchAdminModel": {
        "method": "PATCH",
        "path": "/admin/v1/models/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchAdminModelOffering": {
        "method": "PATCH",
        "path": "/admin/v1/models/{model_id}/offerings/{offering_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchAdminPolicy": {
        "method": "PATCH",
        "path": "/admin/v1/policies/{name}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchAdminPromptTemplate": {
        "method": "PATCH",
        "path": "/admin/v1/prompt-templates/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchAdminProvider": {
        "method": "PATCH",
        "path": "/admin/v1/providers/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchAdminSkillPackage": {
        "method": "PATCH",
        "path": "/admin/v1/skill-packages/{id}",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "patchAnnouncement": {
        "method": "PATCH",
        "path": "/admin/v1/announcements/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "patchBillingGroup": {
        "method": "PATCH",
        "path": "/admin/v1/billing-groups/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "pollSelfHostedWorkerRun": {
        "method": "POST",
        "path": "/v1/self-hosted-workers/runs/poll",
        "security": ((("selfHostedTransport", ()),),),
        "tags": ("internal",),
    },
    "promoteAssetVisibility": {
        "method": "POST",
        "path": "/v1/assets/{asset_type}/{name}/{version}/visibility",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "putAdminAgentSchedule": {
        "method": "PUT",
        "path": "/admin/v1/agent-schedules/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "putAdminAgentUpstream": {
        "method": "PUT",
        "path": "/admin/v1/agent-upstreams/{id}",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "putAdminAgentWorkflow": {
        "method": "PUT",
        "path": "/admin/v1/agent-workflows/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "putAdminApiKey": {
        "method": "PUT",
        "path": "/admin/v1/api-keys/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "putAdminGatewayConfig": {
        "method": "PUT",
        "path": "/admin/v1/gateway-configs/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "putAdminMcpServer": {
        "method": "PUT",
        "path": "/admin/v1/mcp-servers/{name}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "putAdminPolicy": {
        "method": "PUT",
        "path": "/admin/v1/policies/{name}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "putAdminPromptTemplate": {
        "method": "PUT",
        "path": "/admin/v1/prompt-templates/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "putAdminPromptTemplateLabel": {
        "method": "PUT",
        "path": "/admin/v1/prompt-templates/{id}/labels/{label}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "putAdminSkillPackage": {
        "method": "PUT",
        "path": "/admin/v1/skill-packages/{id}",
        "security": ((("AdminBearerAuth", ()),), (("ApiKeyAuth", ()),)),
        "tags": ("Admin",),
    },
    "putAsset": {
        "method": "PUT",
        "path": "/v1/assets/{asset_type}/{name}/{version}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "putAssetChannel": {
        "method": "PUT",
        "path": "/v1/assets/{asset_type}/{name}/channels/{channel}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "putAssetRetentionPolicy": {
        "method": "PUT",
        "path": "/admin/v1/retention-policies/{tenant_id}/{asset_type}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "putProviderCredential": {
        "method": "PUT",
        "path": "/admin/v1/provider-credentials/{alias}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "queryBillingFleet": {
        "method": "GET",
        "path": "/admin/v1/billing-fleet",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "queryTenantData": {
        "method": "POST",
        "path": "/admin/v1/tenant-data/{tenant_id}/query",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "recordAdminSelfHostedWorkerArtifact": {
        "method": "POST",
        "path": "/admin/v1/self-hosted-workers/{id}/artifacts",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "recordAdminSelfHostedWorkerCheckpoint": {
        "method": "POST",
        "path": "/admin/v1/self-hosted-workers/{id}/checkpoints",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "recordAdminSelfHostedWorkerHeartbeat": {
        "method": "POST",
        "path": "/admin/v1/self-hosted-workers/{id}/heartbeat",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "recordAdminSelfHostedWorkerTelemetryEvent": {
        "method": "POST",
        "path": "/admin/v1/self-hosted-workers/{id}/events",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "recordSelfHostedWorkerEvent": {
        "method": "POST",
        "path": "/v1/self-hosted-workers/events",
        "security": ((("selfHostedTransport", ()),),),
        "tags": ("internal",),
    },
    "recordSelfHostedWorkerHeartbeat": {
        "method": "POST",
        "path": "/v1/self-hosted-workers/heartbeat",
        "security": ((("selfHostedTransport", ()),),),
        "tags": ("internal",),
    },
    "registerAdminSelfHostedWorker": {
        "method": "POST",
        "path": "/admin/v1/status",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "registerSelfHostedWorker": {
        "method": "POST",
        "path": "/admin/v1/self-hosted-workers",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "reloadAdminConfig": {
        "method": "POST",
        "path": "/admin/v1/config/reload",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "renderPromptTemplate": {
        "method": "POST",
        "path": "/v1/prompts/{id}/render",
        "security": ((("bearerAuth", ()),),),
        "tags": ("ai-runtime",),
    },
    "replaceAdminModel": {
        "method": "PUT",
        "path": "/admin/v1/models/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "replaceAdminModelOffering": {
        "method": "PUT",
        "path": "/admin/v1/models/{model_id}/offerings/{offering_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "replaceAdminProvider": {
        "method": "PUT",
        "path": "/admin/v1/providers/{id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "replacePlan": {
        "method": "PUT",
        "path": "/admin/v1/plans/{plan_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "replaceProject": {
        "method": "PUT",
        "path": "/admin/v1/projects/{project_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "replaceQuotaPolicy": {
        "method": "PUT",
        "path": "/admin/v1/quota-policies/{scope_type}/{scope_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "replaceSemanticCachePolicy": {
        "method": "PUT",
        "path": "/admin/v1/semantic-cache-policies/{scope_type}/{scope_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "replaceTenantAccount": {
        "method": "PUT",
        "path": "/admin/v1/tenant-accounts/{tenant_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "replaceWorkspace": {
        "method": "PUT",
        "path": "/admin/v1/workspaces/{workspace_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "replayBillingOutboxDeadLetter": {
        "method": "POST",
        "path": "/admin/v1/billing-outbox-dead-letters/{report_id}/replay",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "restoreTenantData": {
        "method": "POST",
        "path": "/admin/v1/tenant-data/{tenant_id}/restore",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "retrieveBatch": {
        "method": "GET",
        "path": "/v1/batches/{batch_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "reviewQuarantinedAsset": {
        "method": "POST",
        "path": "/admin/v1/assets/quarantine/{asset_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "revokeMcpIdentity": {
        "method": "DELETE",
        "path": "/v1/mcp/identity/{server}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "revokeProviderCredential": {
        "method": "DELETE",
        "path": "/admin/v1/provider-credentials/{alias}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "revokeVirtualKey": {
        "method": "DELETE",
        "path": "/admin/v1/virtual-keys/{key_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "revokeVirtualKeyAction": {
        "method": "POST",
        "path": "/admin/v1/virtual-keys/{key_id}/revoke",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "rollbackGuardrailPolicyRevision": {
        "method": "POST",
        "path": "/admin/v1/guardrail-policies/{policy_id}/rollback",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "rotateAdminSelfHostedWorkerIdentity": {
        "method": "POST",
        "path": "/admin/v1/self-hosted-workers/{id}/rotate",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "rotateVirtualKey": {
        "method": "POST",
        "path": "/admin/v1/virtual-keys/{key_id}/rotate",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "runAdminAgentScheduleNow": {
        "method": "POST",
        "path": "/admin/v1/agent-schedules/{id}/run-now",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "sendAgentMessage": {
        "method": "POST",
        "path": "/v1/agents/{name}/message:send",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "serveSite": {
        "method": "GET",
        "path": "/sites/{*rest}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "setAdminDrain": {
        "method": "POST",
        "path": "/admin/v1/drain",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "streamAgentMessage": {
        "method": "POST",
        "path": "/v1/agents/{name}/message:stream",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "submitAgentJob": {
        "method": "POST",
        "path": "/v1/agent-jobs",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "syncProviderModels": {
        "method": "POST",
        "path": "/admin/v1/providers/{id}/sync-models",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "unbindBillingGroupProvider": {
        "method": "DELETE",
        "path": "/admin/v1/billing-groups/{id}/providers/{providerId}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "unbindSiteDomain": {
        "method": "DELETE",
        "path": "/admin/v1/site-domains/{hostname}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "unbindTenantRole": {
        "method": "DELETE",
        "path": "/admin/v1/tenant-roles/{tenant_id}/{role_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-read",),
    },
    "unyankAssetVersion": {
        "method": "DELETE",
        "path": "/v1/assets/{asset_type}/{name}/{version}/yank",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
    "updateAdminPlugin": {
        "method": "PATCH",
        "path": "/admin/v1/plugins/{plugin_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "updatePlan": {
        "method": "PATCH",
        "path": "/admin/v1/plans/{plan_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "updateProject": {
        "method": "PATCH",
        "path": "/admin/v1/projects/{project_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "updateQuotaPolicy": {
        "method": "PATCH",
        "path": "/admin/v1/quota-policies/{scope_type}/{scope_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "updateTenantAccount": {
        "method": "PATCH",
        "path": "/admin/v1/tenant-accounts/{tenant_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "updateWallet": {
        "method": "PATCH",
        "path": "/admin/v1/wallets/{tenant_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "updateWorkspace": {
        "method": "PATCH",
        "path": "/admin/v1/workspaces/{workspace_id}",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "uploadSelfHostedWorkerArtifact": {
        "method": "POST",
        "path": "/v1/self-hosted-workers/artifacts",
        "security": ((("selfHostedTransport", ()),),),
        "tags": ("internal",),
    },
    "uploadSelfHostedWorkerCheckpoint": {
        "method": "POST",
        "path": "/v1/self-hosted-workers/checkpoints",
        "security": ((("selfHostedTransport", ()),),),
        "tags": ("internal",),
    },
    "validateAdminConfig": {
        "method": "POST",
        "path": "/admin/v1/config/validate",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "verifySiteDomain": {
        "method": "POST",
        "path": "/admin/v1/site-domains/{hostname}/verify",
        "security": ((("bearerAuth", ()),),),
        "tags": ("admin-write",),
    },
    "yankAssetVersion": {
        "method": "POST",
        "path": "/v1/assets/{asset_type}/{name}/{version}/yank",
        "security": ((("bearerAuth", ()),),),
        "tags": ("gateway",),
    },
}

ADMIN_OPERATION_IDS: Final[tuple[str, ...]] = (
    "activateGuardrailPolicyRevision",
    "adjustWallet",
    "approveAdminToolApproval",
    "archiveAdminPromptTemplate",
    "archiveGuardrailPolicyRevision",
    "assignTenantPlan",
    "backfillControlStorage",
    "bindBillingGroupProvider",
    "bindSiteDomain",
    "bindTenantRole",
    "chargeWallet",
    "createAdminAgentSchedule",
    "createAdminAgentUpstream",
    "createAdminAgentWorkflow",
    "createAdminApiKey",
    "createAdminGatewayConfig",
    "createAdminMcpServer",
    "createAdminModel",
    "createAdminModelOffering",
    "createAdminPlugin",
    "createAdminPolicy",
    "createAdminPromptTemplate",
    "createAdminProvider",
    "createAdminSkillPackage",
    "createAnnouncement",
    "createBillingGroup",
    "createGuardrailPolicyRevision",
    "createNextGuardrailPolicyRevision",
    "createPaymentMethod",
    "createPermission",
    "createPlan",
    "createProject",
    "createQuotaPolicy",
    "createRole",
    "createSemanticCachePolicy",
    "createTenantAccount",
    "createVirtualKey",
    "createWallet",
    "createWorkspace",
    "deleteAdminAgentSchedule",
    "deleteAdminAgentUpstream",
    "deleteAdminAgentWorkflow",
    "deleteAdminApiKey",
    "deleteAdminGatewayConfig",
    "deleteAdminMcpServer",
    "deleteAdminModel",
    "deleteAdminModelOffering",
    "deleteAdminPlugin",
    "deleteAdminPolicy",
    "deleteAdminPromptTemplateLabel",
    "deleteAdminProvider",
    "deleteAdminSkillPackage",
    "deleteAnnouncement",
    "deleteBillingGroup",
    "deletePaymentMethod",
    "deletePermission",
    "deleteProject",
    "deleteQuotaPolicy",
    "deleteRole",
    "deleteSemanticCachePolicy",
    "deleteWorkspace",
    "denyAdminToolApproval",
    "disableVirtualKey",
    "dryRunGuardrailPolicyRevision",
    "enableVirtualKey",
    "evaluateX402SpendPolicy",
    "expireAdminToolApproval",
    "exportAdminCostRecords",
    "exportAdminRequestLogsJsonl",
    "exportTenantData",
    "forceDeleteAssetVersion",
    "getAdminAgentRunTimeline",
    "getAdminAgentSchedule",
    "getAdminAgentUpstream",
    "getAdminAgentWorkflow",
    "getAdminApiKey",
    "getAdminDrain",
    "getAdminExperiment",
    "getAdminGatewayConfig",
    "getAdminMcpServer",
    "getAdminModel",
    "getAdminModelOffering",
    "getAdminOverview",
    "getAdminPlugin",
    "getAdminPolicy",
    "getAdminPromptTemplate",
    "getAdminProvider",
    "getAdminSelfHostedRunTimeline",
    "getAdminSelfHostedWorker",
    "getAdminSkillPackage",
    "getAdminStatus",
    "getAdminToolApproval",
    "getAnnouncement",
    "getAssetRetentionPolicy",
    "getBillingGroup",
    "getEffectiveX402SpendPolicy",
    "getGuardrailInvestigation",
    "getGuardrailPolicyRevision",
    "getPaymentAttemptLinks",
    "getPermission",
    "getPlan",
    "getProject",
    "getQuotaPolicy",
    "getRole",
    "getSemanticCachePolicy",
    "getSiteDomain",
    "getTenantAccount",
    "getTenantResolvedDefaults",
    "getVirtualKey",
    "getWallet",
    "getWorkspace",
    "importModelCatalog",
    "invalidateSemanticCachePolicy",
    "listAdminAgentCostBurn",
    "listAdminAgentRuns",
    "listAdminAgentScheduleFires",
    "listAdminAgentSchedules",
    "listAdminAgentUpstreams",
    "listAdminAgentWorkflows",
    "listAdminApiKeys",
    "listAdminAuditEvents",
    "listAdminBillingEventsCompat",
    "listAdminCostRecords",
    "listAdminExperiments",
    "listAdminExtensions",
    "listAdminFrameworkAdapters",
    "listAdminGatewayConfigs",
    "listAdminManagedWorkerSessions",
    "listAdminManagedWorkers",
    "listAdminMcpServers",
    "listAdminMeteringEvents",
    "listAdminMeteringExportStatus",
    "listAdminModelOfferings",
    "listAdminModels",
    "listAdminObservability",
    "listAdminObservedAgentActivity",
    "listAdminPluginTools",
    "listAdminPlugins",
    "listAdminPolicies",
    "listAdminPromptTemplateLabels",
    "listAdminPromptTemplates",
    "listAdminProviderHealth",
    "listAdminProviderModels",
    "listAdminProviders",
    "listAdminRequestLogs",
    "listAdminSelfHostedWorkerRecords",
    "listAdminSelfHostedWorkerTelemetryEvents",
    "listAdminSelfHostedWorkers",
    "listAdminSkillPackages",
    "listAdminSpendAnomalies",
    "listAdminTenants",
    "listAdminToolApprovals",
    "listAdminToolSessionEvents",
    "listAdminTools",
    "listAdminUsageAggregates",
    "listAnnouncements",
    "listBillingGroups",
    "listBillingOutboxDeadLetters",
    "listFleetAssets",
    "listGuardrailEvaluations",
    "listGuardrailPolicyRevisionHistory",
    "listGuardrailPolicyRevisions",
    "listGuardrailPolicyRevisionsByPolicy",
    "listPaymentAttempts",
    "listPaymentMethods",
    "listPermissions",
    "listPlans",
    "listProjects",
    "listProviderCredentials",
    "listQuarantinedAssets",
    "listQuotaPolicies",
    "listRoles",
    "listSemanticCachePolicies",
    "listSharedBillingGroups",
    "listSiteDomains",
    "listTenantAccounts",
    "listTenantRoles",
    "listUsageReports",
    "listVirtualKeys",
    "listWalletLedger",
    "listWallets",
    "listWorkspaces",
    "listX402SpendPolicies",
    "migrateTenantStorage",
    "patchAdminAgentSchedule",
    "patchAdminAgentUpstream",
    "patchAdminAgentWorkflow",
    "patchAdminApiKey",
    "patchAdminGatewayConfig",
    "patchAdminMcpServer",
    "patchAdminModel",
    "patchAdminModelOffering",
    "patchAdminPolicy",
    "patchAdminPromptTemplate",
    "patchAdminProvider",
    "patchAdminSkillPackage",
    "patchAnnouncement",
    "patchBillingGroup",
    "putAdminAgentSchedule",
    "putAdminAgentUpstream",
    "putAdminAgentWorkflow",
    "putAdminApiKey",
    "putAdminGatewayConfig",
    "putAdminMcpServer",
    "putAdminPolicy",
    "putAdminPromptTemplate",
    "putAdminPromptTemplateLabel",
    "putAdminSkillPackage",
    "putAssetRetentionPolicy",
    "putProviderCredential",
    "queryBillingFleet",
    "queryTenantData",
    "recordAdminSelfHostedWorkerArtifact",
    "recordAdminSelfHostedWorkerCheckpoint",
    "recordAdminSelfHostedWorkerHeartbeat",
    "recordAdminSelfHostedWorkerTelemetryEvent",
    "registerAdminSelfHostedWorker",
    "registerSelfHostedWorker",
    "reloadAdminConfig",
    "replaceAdminModel",
    "replaceAdminModelOffering",
    "replaceAdminProvider",
    "replacePlan",
    "replaceProject",
    "replaceQuotaPolicy",
    "replaceSemanticCachePolicy",
    "replaceTenantAccount",
    "replaceWorkspace",
    "replayBillingOutboxDeadLetter",
    "restoreTenantData",
    "reviewQuarantinedAsset",
    "revokeProviderCredential",
    "revokeVirtualKey",
    "revokeVirtualKeyAction",
    "rollbackGuardrailPolicyRevision",
    "rotateAdminSelfHostedWorkerIdentity",
    "rotateVirtualKey",
    "runAdminAgentScheduleNow",
    "setAdminDrain",
    "syncProviderModels",
    "unbindBillingGroupProvider",
    "unbindSiteDomain",
    "unbindTenantRole",
    "updateAdminPlugin",
    "updatePlan",
    "updateProject",
    "updateQuotaPolicy",
    "updateTenantAccount",
    "updateWallet",
    "updateWorkspace",
    "validateAdminConfig",
    "verifySiteDomain",
)
