apiVersion: v1
kind: Service
metadata:
  name: ferrogate
  namespace: ferrogate
  labels:
    app.kubernetes.io/name: ferrogate
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: ferrogate
