// Token4AI Cloud Attribution
// Developed by the commercial cloud service company represented by https://token4ai.cloud.
// Author: jamesduan (X: https://x.com/JamesDuanL)
// Created: 2026-07-24
// description: Token4AI Cloud, FerroGate AI Gateway, Rust API Gateway, agent-native AI traffic infrastructure.

//! Command-reference generator (issue #365).
//!
//! Renders the FULL assembled `ferrogate` command tree — the derived commands
//! plus the generic `ctl <group> <verb>` resource families (#361–#365) — into a
//! deterministic Markdown document committed at `docs/cli-reference.md`. The
//! reference is produced from [`command_tree::assembled_command`], the exact
//! `clap::Command` the binary parses, so it is a faithful, drift-checked
//! description of what the shipped CLI accepts.
//!
//! Determinism is deliberate so the companion sync test in `reference_test.rs`
//! can fail on drift:
//! * the version string is intentionally omitted (a version bump must not churn
//!   the reference),
//! * every help string is whitespace-collapsed onto a single line, and
//! * subcommands/arguments are emitted in clap's own stable declaration order.
//!
//! Regenerate after changing the command surface with:
//! ```sh
//! FERROGATE_REGENERATE_DOCS=1 cargo test -p ferrogate-cli reference
//! ```

use std::fmt::Write as _;

use clap::{Arg, Command};

use crate::command_tree;

/// Static preamble (title + orientation + examples). Constant text, so it
/// stays trivially in sync with the generated body below it.
const PREAMBLE: &str = "\
# FerroGate CLI command reference

<!--
Generated by `crates/ferrogate-cli/src/reference.rs`; do NOT edit by hand.
Regenerate after changing the command surface:
    FERROGATE_REGENERATE_DOCS=1 cargo test -p ferrogate-cli reference
The `reference` sync test fails CI when this file drifts from the command tree.
-->

This is the full `ferrogate` command surface the shipped binary assembles: the
derived top-level commands plus the generic Control Plane API resource families
mounted under `ferrogate ctl <group> <verb>` (issues #361-#365), whose subtree
is derived from the `ferrogate-cli-core` registry metadata. Shell completions
(`ferrogate completions <shell>`) are generated from this same command tree.

## Examples

```sh
# Install shell completions (bash/zsh/fish/powershell/elvish supported):
ferrogate completions bash > /etc/bash_completion.d/ferrogate

# Point the client at a Control Plane API endpoint, then use it by default:
ferrogate context create prod --endpoint https://control.example.com --token-env FERROGATE_TOKEN --use

# List a resource family through the generic `ctl` tree:
ferrogate ctl tenants list --output json

# Read system status through the shared typed client:
ferrogate ops status
```
";

/// Render the whole command reference document (preamble + generated tree).
/// Ends with exactly one trailing newline so the committed file is POSIX-clean
/// (no `git diff --check` blank-line-at-EOF warning).
pub(crate) fn render_reference() -> String {
    let registry = command_tree::resource_registry();
    let command = command_tree::assembled_command(&registry);

    let mut out = String::new();
    out.push_str(PREAMBLE);
    out.push('\n');
    render_command(&command, command.get_name().to_string(), 0, &mut out);

    // The tree walker leaves trailing blank lines between sections; normalize
    // the whole document to a single terminating newline.
    let mut doc = out.trim_end().to_string();
    doc.push('\n');
    doc
}

/// Emit one command node (pre-order) then recurse into its visible subcommands.
/// `path` is the full invocation path (e.g. `ferrogate ctl tenants list`);
/// `depth` drives the Markdown heading level (capped at h6).
fn render_command(command: &Command, path: String, depth: usize, out: &mut String) {
    let heading = "#".repeat((depth + 2).min(6));
    let _ = writeln!(out, "\n{heading} `{path}`\n");

    if let Some(about) = command
        .get_long_about()
        .or_else(|| command.get_about())
        .map(|about| collapse_whitespace(&about.to_string()))
    {
        if !about.is_empty() {
            let _ = writeln!(out, "{about}\n");
        }
    }

    let aliases: Vec<&str> = command.get_visible_aliases().collect();
    if !aliases.is_empty() {
        let rendered = aliases
            .iter()
            .map(|alias| format!("`{alias}`"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "Aliases: {rendered}\n");
    }

    let (positionals, options): (Vec<&Arg>, Vec<&Arg>) = command
        .get_arguments()
        .filter(|arg| !arg.is_hide_set() && !is_builtin_arg(arg))
        .partition(|arg| arg.is_positional());

    if !positionals.is_empty() {
        out.push_str("Arguments:\n\n");
        for arg in &positionals {
            let _ = writeln!(out, "- {}", render_positional(arg));
        }
        out.push('\n');
    }

    if !options.is_empty() {
        out.push_str("Options:\n\n");
        for arg in &options {
            let _ = writeln!(out, "- {}", render_option(arg));
        }
        out.push('\n');
    }

    let subcommands: Vec<&Command> = command
        .get_subcommands()
        .filter(|sub| !sub.is_hide_set())
        .collect();
    if !subcommands.is_empty() {
        out.push_str("Subcommands:\n\n");
        for sub in &subcommands {
            let about = sub
                .get_about()
                .map(|about| collapse_whitespace(&about.to_string()))
                .unwrap_or_default();
            let _ = writeln!(out, "- `{}` — {}", sub.get_name(), about);
        }
    }

    for sub in subcommands {
        render_command(sub, format!("{path} {}", sub.get_name()), depth + 1, out);
    }
}

/// The clap-injected `--help` / `--version` args are structural noise in a
/// reference, so they are filtered out.
fn is_builtin_arg(arg: &Arg) -> bool {
    matches!(arg.get_id().as_str(), "help" | "version")
}

/// Render a positional argument as `` `<NAME>` — help ``, with `...` when it
/// accepts multiple values.
fn render_positional(arg: &Arg) -> String {
    let name = value_placeholder(arg).unwrap_or_else(|| arg.get_id().as_str().to_uppercase());
    let ellipsis = if accepts_many(arg) { "..." } else { "" };
    let mut rendered = format!("`<{name}>{ellipsis}`");
    append_help(&mut rendered, &arg_help(arg));
    rendered
}

/// Render an option as `` `-x, --long <VALUE>` — help [env: VAR] ``.
fn render_option(arg: &Arg) -> String {
    let mut flags = Vec::new();
    if let Some(short) = arg.get_short() {
        flags.push(format!("-{short}"));
    }
    if let Some(long) = arg.get_long() {
        flags.push(format!("--{long}"));
    }
    let mut signature = flags.join(", ");
    if let Some(placeholder) = value_placeholder(arg) {
        signature.push_str(&format!(" <{placeholder}>"));
    }

    let mut rendered = format!("`{signature}`");
    append_help(&mut rendered, &arg_help(arg));
    if let Some(env) = arg.get_env() {
        rendered.push_str(&format!(" [env: {}]", env.to_string_lossy()));
    }
    rendered
}

/// Append `— help` only when the arg carries help text, so an undocumented flag
/// does not leave a dangling em dash.
fn append_help(rendered: &mut String, help: &str) {
    if !help.is_empty() {
        rendered.push_str(&format!(" — {help}"));
    }
}

/// The value placeholder for an option/positional that takes a value, or `None`
/// for a boolean flag / counter. The action is the authoritative signal:
/// clap auto-derives a value name even for `SetTrue` flags, so consulting the
/// value name first would spuriously label a flag as value-taking. Prefers an
/// explicit `value_name`, falling back to the upper-cased arg id.
fn value_placeholder(arg: &Arg) -> Option<String> {
    if !arg.get_action().takes_values() {
        return None;
    }
    if let Some(first) = arg.get_value_names().and_then(|names| names.first()) {
        return Some(first.to_string());
    }
    Some(arg.get_id().as_str().to_uppercase())
}

/// Whether the arg accepts more than one value (a `Vec` field / repeatable).
fn accepts_many(arg: &Arg) -> bool {
    matches!(arg.get_num_args(), Some(range) if range.max_values() > 1)
}

/// Short help for an arg, whitespace-collapsed, falling back to long help.
fn arg_help(arg: &Arg) -> String {
    arg.get_help()
        .or_else(|| arg.get_long_help())
        .map(|help| collapse_whitespace(&help.to_string()))
        .unwrap_or_default()
}

/// Collapse every run of whitespace (including the embedded newlines clap keeps
/// from multi-line doc comments) into a single space, so each help string is a
/// stable single line in the reference.
fn collapse_whitespace(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
#[path = "reference_test.rs"]
mod reference_test;
